language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
rvm:
  - 2.6.1
services:
  - postgresql
addons:
  postgresql: '9.6'
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn install
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle install  --jobs=3 --retry=3
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rspec
  - yarn test