language: ruby
rvm:
  - 2.4.6
services:
  - postgresql
addons:
  postgresql: '9.6'
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle install  --jobs=3 --retry=3
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rspec