import axios from 'axios';

/* 
  You can cancel a axios request by using cancel token. 
  getSource will return a source.
  To access the token, use source.token.
  To cancel the request, use source.cancel('Cancelation message')
*/
const getSource = () => axios.CancelToken.source();

/*
  When you cancel a axios request, the promise will reject.
  Then, you have to treat the errors accordingly. Use checkError 
  to check if the error was generated by promise cancelation.
*/
const checkError = err => axios.isCancel(err);

export const Axios = {
  getSource,
  checkError
};
