development: &default
  adapter: postgresql
  host: localhost
  username: gafeol
  password: papaapatia
  database: development_database
  pool: 5
  timeout: 5000

test:
  <<: *default
  adapter: postgresql
  username: gafeol
  password: papaapatia
  database: test_database
